version: 2
jobs:
  build-cocoapods:
    macos:
      xcode: "11.0"
    steps:
      - checkout
      - run:
          name: Install cocoapods
          command: sudo gem install cocoapods -v 1.8.4
      - run:
          name: Install pods
          command: pod install
          
workflows:
  version: 2
  build-and-test-with-cocoapods:
    jobs:
      - build-cocoapods
